owner: typicalninja493 # GitHub username
repo: uptime # GitHub repository name
user-agent: typicalninja493
sites: # List of endpoints to track
  - name: Main website
    url: https://www.axixbot.tk/
  - name: Axix(bot)
    url: $BOT
  - name: Docs
    url: $DOCS
  - name: Vote webhook
    url: $VWEBHOOK
assignees: # Users to assign downtime issues (optional)
  - typicalninja493
status-website: # Status website (optional)
  baseUrl: /uptime
  name: Axix
  logoUrl: https://www.axixbot.tk/css/favicon.ico


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
