# Change these first
owner: typicalninja493 # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
 - name: Google
    url: https://www.google.com

status-website:
 baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status
  introTitle: "Welcome to our official status page


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
