owner: typicalninja493 # GitHub username
repo: uptime # GitHub repository name
user-agent: typicalninja493
sites: # List of endpoints to track
  - name: Main website
    url: https://www.axixbot.tk/
assignees: # Users to assign downtime issues (optional)
  - typicalninja493
status-website: # Status website (optional)
  baseUrl: /uptime
  name: Uptime


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
