owner: typicalninja493 # GitHub username
repo: uptime # GitHub repository name
user-agent: typicalninja493
sites: # List of endpoints to track
  - name: Main website
    url: https://axixbot.cf/
  - name: Docs
    url: $DOCS
  - name: Vote webhook
    url: $VWEBHOOK
  - name: Axix bot
    url: $BOT
  - name: Lavalink Node1
    url: $lava
    expectedStatusCodes:
      - 200
      - 401
      - 404
      - 500
      - 403
assignees: # Users to assign downtime issues (optional)
  - typicalninja493
status-website: # Status website (optional)
  cname: status.axixbot.cf
  name: Axix
  logoUrl: https://axixbot.tk/css/favicon.ico

i18n:
  footer: powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
